spec:
  containers:
  - name: node-app
    image: naren5464/node-app:latest  # YOUR REAL IMAGE
    ports:
    - containerPort: 3000
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
